//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCompras
    {
        public TblCompras()
        {
            this.DetalleCompra = new HashSet<DetalleCompra>();
        }
    
        public int IdCompra { get; set; }
        public string NoFactura { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public int IdProveedor { get; set; }
        public Nullable<bool> Anulada { get; set; }
        public string MotivoAnulada { get; set; }
        public Nullable<System.DateTime> FechaAnulada { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual ICollection<DetalleCompra> DetalleCompra { get; set; }
    }
}
