//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFactura
    {
        public TblFactura()
        {
            this.TblDetalleFactura = new HashSet<TblDetalleFactura>();
        }
    
        public int Id { get; set; }
        public int IdMoneda { get; set; }
        public string CodFactura { get; set; }
        public string DatosCliente { get; set; }
        public string Estado { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Iva { get; set; }
        public decimal Total { get; set; }
        public Nullable<decimal> Efectivo { get; set; }
        public Nullable<decimal> Vuelto { get; set; }
        public int IdUsuarioCrea { get; set; }
        public Nullable<int> IdUsuarioModifica { get; set; }
        public System.DateTime FechaCrea { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual TblMoneda TblMoneda { get; set; }
        public virtual ICollection<TblDetalleFactura> TblDetalleFactura { get; set; }
    }
}
