//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductosAlmacen
    {
        public TblProductosAlmacen()
        {
            this.TblProductosAlmacenDet = new HashSet<TblProductosAlmacenDet>();
        }
    
        public int Id { get; set; }
        public int IdProveedor { get; set; }
        public string NumRecibo { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public Nullable<bool> ExcentoIva { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int IdUsuarioCrea { get; set; }
        public Nullable<int> IdUsuarioModifica { get; set; }
        public System.DateTime FechaCrea { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual TblProveedores TblProveedores { get; set; }
        public virtual ICollection<TblProductosAlmacenDet> TblProductosAlmacenDet { get; set; }
    }
}
