//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductos
    {
        public TblProductos()
        {
            this.TblModelo = new HashSet<TblModelo>();
        }
    
        public int Id { get; set; }
        public int IdAlmacen { get; set; }
        public int IdCategoria { get; set; }
        public int IdMarca { get; set; }
        public int IdUsuarioCrea { get; set; }
        public Nullable<int> IdUsuarioModifica { get; set; }
        public System.DateTime FechaCrea { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual TblAlmacen TblAlmacen { get; set; }
        public virtual TblCategorias TblCategorias { get; set; }
        public virtual TblMarca TblMarca { get; set; }
        public virtual ICollection<TblModelo> TblModelo { get; set; }
    }
}
