//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductosAlmacenDet
    {
        public int Id { get; set; }
        public int IdProductosAlmacen { get; set; }
        public int IdModelo { get; set; }
        public string CodProducto { get; set; }
        public string Serie { get; set; }
        public string IMEI { get; set; }
        public bool Estado { get; set; }
        public int PrecioC { get; set; }
        public Nullable<int> PrecioV { get; set; }
        public string CodFactura { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string MotivoBaja { get; set; }
        public int IdUsuarioCrea { get; set; }
        public Nullable<int> IdUsuarioModifica { get; set; }
        public System.DateTime FechaCrea { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual TblProductosAlmacen TblProductosAlmacen { get; set; }
        public virtual TblModelo TblModelo { get; set; }
    }
}
